In [2]:
import pandas as pd
import numpy as np

Q1 Pandas Cersion

In [2]:
pd.__version__

'3.0.6'

Acquiring the Data

In [3]:
df = pd.read_csv("https://raw.githubusercontent.com/DataTalksClub/machine-learning-zoomcamp/main/cohorts/2026/data/car_fuel_efficiency_2026.csv")

In [6]:
df.head()

,model_year,origin,fuel_type,drivetrain,num_doors,engine_displacement,num_cylinders,horsepower,vehicle_weight,acceleration,fuel_efficiency_mpg
0,2006,Europe,Gasoline,Front-wheel drive,4,2180,6,243.0,3870,NaN,31.9
1,2008,Europe,Diesel,Front-wheel drive,4,2390,6,272.0,4210,NaN,31.3
2,1996,Asia,Gasoline,Front-wheel drive,5,2320,6,267.0,4240,17.3,27.5
3,1989,Europe,Gasoline,Front-wheel drive,4,2130,6,258.0,4490,18.7,28.5
4,1994,USA,Diesel,Front-wheel drive,3,2580,7,304.0,4510,17.5,31.0

Q2 Record Count

In [10]:
df.shape[0]

10000

In [ ]:
Q2 Fuel Types

In [11]:
df["fuel_type"].nunique()

3

In [ ]:
Q4 Missing Values

In [12]:
df.isnull().sum()

model_year               0
origin                   0
fuel_type                0
drivetrain               0
num_doors                0
engine_displacement      0
num_cylinders            0
horsepower             877
vehicle_weight           0
acceleration           264
fuel_efficiency_mpg      0
dtype: int64

In [ ]:
Q5 Max Fuel Efficiency

In [13]:
df["fuel_efficiency_mpg"].max()

np.float64(41.2)

In [ ]:
Q6 Median Value of Horsepower

In [14]:
df["horsepower"].median()

np.float64(254.0)

In [15]:
df["horsepower"].mode()

0    252.0
Name: horsepower, dtype: float64

In [18]:
df["horsepower"] = df["horsepower"].fillna(df["horsepower"].mode()[0])

In [19]:
df["horsepower"].median()

np.float64(252.0)

Q7 Sum of Weights

In [21]:
# All cars from Asia
df[
    df["origin"] == "Asia"
]

,model_year,origin,fuel_type,drivetrain,num_doors,engine_displacement,num_cylinders,horsepower,vehicle_weight,acceleration,fuel_efficiency_mpg
2,1996,Asia,Gasoline,Front-wheel drive,5,2320,6,267.0,4240,17.3,27.5
6,1992,Asia,Gasoline,Front-wheel drive,2,2270,6,250.0,4310,21.7,26.8
8,1997,Asia,Gasoline,Rear-wheel drive,3,2330,6,251.0,4230,19.5,30.9
10,1978,Asia,Gasoline,All-wheel drive,3,2410,6,252.0,4420,19.5,26.8
15,2007,Asia,Diesel,Front-wheel drive,4,2170,5,226.0,3950,18.0,35.4
...,...,...,...,...,...,...,...,...,...,...,...
9984,2011,Asia,Gasoline,Front-wheel drive,3,2410,6,256.0,4610,20.2,32.4
9987,2004,Asia,Diesel,All-wheel drive,3,2180,6,266.0,4530,18.6,29.0
9990,1975,Asia,Diesel,Front-wheel drive,4,1940,6,236.0,3630,19.7,32.4
9994,1993,Asia,Gasoline,Rear-wheel drive,2,2360,6,257.0,4610,22.2,30.1
9996,1993,Asia,Gasoline,All-wheel drive,2,2300,6,244.0,4370,19.0,30.0

In [4]:
# Only columns vehicle_weight and model_year
vw_my = df[
    ["vehicle_weight", "model_year"]
]
print(vw_my)

      vehicle_weight  model_year
0               3870        2006
1               4210        2008
2               4240        1996
3               4490        1989
4               4510        1994
...              ...         ...
9995            4690        2005
9996            4370        1993
9997            4590        2014
9998            4450        2004
9999            4370        2011

[10000 rows x 2 columns]

In [24]:
# First 7 values
vw_my.head(n=7)

   vehicle_weight  model_year
0            3870        2006
1            4210        2008
2            4240        1996
3            4490        1989
4            4510        1994
5            4260        2007
6            4310        1992

In [5]:
# Underlying NumPy array
X = vw_my.values
print(X)

[[3870 2006]
 [4210 2008]
 [4240 1996]
 ...
 [4590 2014]
 [4450 2004]
 [4370 2011]]

In [10]:
# Matrix-matrix multiplication between the transpose of X and X
# XTX = X.dot(X.T) # Wrong per thread in Slack
XTX = X.T.dot(X) # Solution offered by sSlack thread
print(XTX)

[[184471218600  85715315370]
 [ 85715315370  39984000479]]

In [11]:
# Inverse of XTX
XTX_inv = np.linalg.inv(XTX)
print(XTX_inv)

[[ 1.38920141e-09 -2.97808713e-09]
 [-2.97808713e-09  6.40925557e-09]]

In [12]:
# Checking determinant of XTX
np.linalg.det(XTX)

np.float64(2.878200388555498e+19)

In [13]:
np.linalg.pinv(XTX)

array([[ 1.38920141e-09, -2.97808713e-09],
       [-2.97808713e-09,  6.40925557e-09]])