Introduction to Pandas

In [2]:
import numpy as np
import pandas as pd

The data is a list of lists - each sublist is a row in the table, so each row is a car - and a separate variable that defines the column names

In [4]:
pd.__version__

'3.0.6'

In [4]:
data = [
    ['Nissan', 'Stanza', 1991, 138, 4, 'MANUAL', 'sedan', 2000],
    ['Hyundai', 'Sonata', 2017, None, 4, 'AUTOMATIC', 'Sedan', 27150],
    ['Lotus', 'Elise', 2010, 218, 4, 'MANUAL', 'convertible', 54990],
    ['GMC', 'Acadia',  2017, 194, 4, 'AUTOMATIC', '4dr SUV', 34450],
    ['Nissan', 'Frontier', 2017, 261, 6, 'MANUAL', 'Pickup', 32340],
]

columns = [
    'Make', 'Model', 'Year', 'Engine HP', 'Engine Cylinders',
    'Transmission Type', 'Vehicle_Style', 'MSRP'
]

Now we can turn it into a DataFrame using the DataFrame constructor.

In [5]:
df = pd.DataFrame(data, columns=columns)

In [4]:
df

,Make,Model,Year,Engine HP,Engine Cylinders,Transmission Type,Vehicle_Style,MSRP
0,Nissan,Stanza,1991,138.0,4,MANUAL,sedan,2000
1,Hyundai,Sonata,2017,NaN,4,AUTOMATIC,Sedan,27150
2,Lotus,Elise,2010,218.0,4,MANUAL,convertible,54990
3,GMC,Acadia,2017,194.0,4,AUTOMATIC,4dr SUV,34450
4,Nissan,Frontier,2017,261.0,6,MANUAL,Pickup,32340

In [5]:
df.head(n=2)

,Make,Model,Year,Engine HP,Engine Cylinders,Transmission Type,Vehicle_Style,MSRP
0,Nissan,Stanza,1991,138.0,4,MANUAL,sedan,2000
1,Hyundai,Sonata,2017,NaN,4,AUTOMATIC,Sedan,27150

Each column is a 'series'

In [6]:
df.Make

0     Nissan
1    Hyundai
2      Lotus
3        GMC
4     Nissan
Name: Make, dtype: str

Brackets option

In [7]:
df['Engine HP']

0    138.0
1      NaN
2    218.0
3    194.0
4    261.0
Name: Engine HP, dtype: float64

For multiple columns, we put a list inside the brackets, thus double brackets

In [8]:
df[['Make', 'Model', 'MSRP']]

      Make     Model   MSRP
0   Nissan    Stanza   2000
1  Hyundai    Sonata  27150
2    Lotus     Elise  54990
3      GMC    Acadia  34450
4   Nissan  Frontier  32340

In [9]:
df['id'] = [1, 2, 3, 4, 5]

In [10]:
df

,Make,Model,Year,Engine HP,Engine Cylinders,Transmission Type,Vehicle_Style,MSRP,id
0,Nissan,Stanza,1991,138.0,4,MANUAL,sedan,2000,1
1,Hyundai,Sonata,2017,NaN,4,AUTOMATIC,Sedan,27150,2
2,Lotus,Elise,2010,218.0,4,MANUAL,convertible,54990,3
3,GMC,Acadia,2017,194.0,4,AUTOMATIC,4dr SUV,34450,4
4,Nissan,Frontier,2017,261.0,6,MANUAL,Pickup,32340,5

### Index

In [11]:
df.index

RangeIndex(start=0, stop=5, step=1)

Access an element by index.

In [12]:
 df.loc[1]

Make                   Hyundai
Model                   Sonata
Year                      2017
Engine HP                  NaN
Engine Cylinders             4
Transmission Type    AUTOMATIC
Vehicle_Style            Sedan
MSRP                     27150
id                           2
Name: 1, dtype: object

In [13]:
df.index = ['a', 'b', 'c', 'd', 'e']

In [14]:
df

,Make,Model,Year,Engine HP,Engine Cylinders,Transmission Type,Vehicle_Style,MSRP,id
a,Nissan,Stanza,1991,138.0,4,MANUAL,sedan,2000,1
b,Hyundai,Sonata,2017,NaN,4,AUTOMATIC,Sedan,27150,2
c,Lotus,Elise,2010,218.0,4,MANUAL,convertible,54990,3
d,GMC,Acadia,2017,194.0,4,AUTOMATIC,4dr SUV,34450,4
e,Nissan,Frontier,2017,261.0,6,MANUAL,Pickup,32340,5

In [15]:
df.iloc[[1, 2, 4]]

,Make,Model,Year,Engine HP,Engine Cylinders,Transmission Type,Vehicle_Style,MSRP,id
b,Hyundai,Sonata,2017,NaN,4,AUTOMATIC,Sedan,27150,2
c,Lotus,Elise,2010,218.0,4,MANUAL,convertible,54990,3
e,Nissan,Frontier,2017,261.0,6,MANUAL,Pickup,32340,5

In [16]:
df = df.reset_index(drop=True)

In [17]:
df

,Make,Model,Year,Engine HP,Engine Cylinders,Transmission Type,Vehicle_Style,MSRP,id
0,Nissan,Stanza,1991,138.0,4,MANUAL,sedan,2000,1
1,Hyundai,Sonata,2017,NaN,4,AUTOMATIC,Sedan,27150,2
2,Lotus,Elise,2010,218.0,4,MANUAL,convertible,54990,3
3,GMC,Acadia,2017,194.0,4,AUTOMATIC,4dr SUV,34450,4
4,Nissan,Frontier,2017,261.0,6,MANUAL,Pickup,32340,5

### Element-wise operations

In [18]:
df['Engine HP'] * 2

0    276.0
1      NaN
2    436.0
3    388.0
4    522.0
Name: Engine HP, dtype: float64

In [19]:
df['Year'] >= 2015

0    False
1     True
2    False
3     True
4     True
Name: Year, dtype: bool

### Filtering
Inner brackets returns a new boolien Series with False and True values. The outer brackets look at the values and returns a data frame containing only True values.

In [20]:
df[
    df['Year'] >= 2015
]

,Make,Model,Year,Engine HP,Engine Cylinders,Transmission Type,Vehicle_Style,MSRP,id
1,Hyundai,Sonata,2017,NaN,4,AUTOMATIC,Sedan,27150,2
3,GMC,Acadia,2017,194.0,4,AUTOMATIC,4dr SUV,34450,4
4,Nissan,Frontier,2017,261.0,6,MANUAL,Pickup,32340,5

In [21]:
df[
    df['Make'] == 'Nissan'
    ]

,Make,Model,Year,Engine HP,Engine Cylinders,Transmission Type,Vehicle_Style,MSRP,id
0,Nissan,Stanza,1991,138.0,4,MANUAL,sedan,2000,1
4,Nissan,Frontier,2017,261.0,6,MANUAL,Pickup,32340,5

Combining conditions:

In [24]:
df[
    (df['Make'] == 'Nissan') & (df['Year'] >= 2015)
        ]

,Make,Model,Year,Engine HP,Engine Cylinders,Transmission Type,Vehicle_Style,MSRP,id
4,Nissan,Frontier,2017,261.0,6,MANUAL,Pickup,32340,5